### ISSUE TITLE
Panic when printing a report containing source code with debug

### ISSUE THREAD

**Issue by rster2002** [zkat/miette#230]
Hi!

I have been trying to print a report using:

```rust
println!("{:?}", Report::new(own_error));
```

`own_error` is an error used throughout my application and implements the `Diagnostic` trait. I've also tried to print without any labels, and just the source code, but still the same issue.

Some information about my environment:
* cargo 1.66.0 (d65d197ad 2022-11-15)
* rustc 1.66.0 (69f9c33d7 2022-12-12)
* miette 5.5.0, with the `fancy` feature enabled

<details>
<summary>Stack trace</summary>
<br>

```
thread 'main' panicked at 'attempt to add with overflow', /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/source_impls.rs:64:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
   3: miette::source_impls::context_info
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/source_impls.rs:64:22
   4: miette::source_impls::<impl miette::protocol::SourceCode for [u8]>::read_span
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/source_impls.rs:106:24
   5: miette::source_impls::<impl miette::protocol::SourceCode for str>::read_span
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/source_impls.rs:140:9
   6: miette::source_impls::<impl miette::protocol::SourceCode for alloc::string::String>::read_span
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/source_impls.rs:168:9
   7: miette::handlers::graphical::GraphicalReportHandler::render_snippets::{{closure}}
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/handlers/graphical.rs:315:29
   8: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/adapters/map.rs:91:28
   9: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/traits/iterator.rs:2238:21
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/adapters/map.rs:117:9
  11: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/adapters/mod.rs:195:9
  12: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/traits/iterator.rs:2299:9
  13: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/adapters/mod.rs:178:9
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/vec/spec_from_iter.rs:33:9
  16: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/vec/mod.rs:2757:9
  17: core::iter::traits::iterator::Iterator::collect
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/traits/iterator.rs:1836:9
  18: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:2075:49
  19: core::iter::adapters::try_process
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/adapters/mod.rs:164:17
  20: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:2075:9
  21: core::iter::traits::iterator::Iterator::collect
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/iter/traits/iterator.rs:1836:9
  22: miette::handlers::graphical::GraphicalReportHandler::render_snippets
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/handlers/graphical.rs:312:36
  23: miette::handlers::graphical::GraphicalReportHandler::render_report
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/handlers/graphical.rs:157:9
  24: <miette::handlers::graphical::GraphicalReportHandler as miette::eyreish::ReportHandler>::debug
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/handlers/graphical.rs:814:9
  25: <miette::handler::MietteHandler as miette::eyreish::ReportHandler>::debug
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/handler.rs:321:9
  26: miette::eyreish::fmt::<impl miette::eyreish::error::ErrorImpl<()>>::debug::{{closure}}
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/eyreish/fmt.rs:17:28
  27: core::option::Option<T>::map
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:925:29
  28: miette::eyreish::fmt::<impl miette::eyreish::error::ErrorImpl<()>>::debug
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/eyreish/fmt.rs:14:9
  29: miette::eyreish::error::<impl core::fmt::Debug for miette::eyreish::Report>::fmt
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.5.0/src/eyreish/error.rs:454:18
  30: core::fmt::write
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
  31: std::io::Write::write_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
  32: <&std::io::stdio::Stdout as std::io::Write>::write_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/stdio.rs:716:9
  33: <std::io::stdio::Stdout as std::io::Write>::write_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/stdio.rs:690:9
  34: std::io::stdio::print_to
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/stdio.rs:1008:21
  35: std::io::stdio::_print
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/stdio.rs:1075:5
  36: rust_application::error::wrap_err::wrap_err
             at ./src/error/wrap_err.rs:34:5
  37: <rust_application::input_file::block::readers::selector_reader::selector_argument_reader::selector_argument_validator::duplicate_validator::DuplicateValidator as rust_application::input_file::block::readers::selector_reader::selector_argument_reader::selector_argument_validator::argument_validator::ArgumentValidator>::check_argument_entry
             at ./src/input_file/block/readers/selector_reader/selector_argument_reader/selector_argument_validator/duplicate_validator.rs:46:24
  38: rust_application::input_file::block::readers::selector_reader::selector_argument_reader::selector_argument_validator::SelectorArgumentValidator::read_argument_entry
             at ./src/input_file/block/readers/selector_reader/selector_argument_reader/selector_argument_validator.rs:60:13
  39: rust_application::input_file::block::readers::selector_reader::selector_argument_reader::SelectorArgumentReader::validate_arguments
             at ./src/input_file/block/readers/selector_reader/selector_argument_reader.rs:84:26
  40: rust_application::input_file::block::readers::selector_reader::selector_argument_reader::SelectorArgumentReader::get_arguments
             at ./src/input_file/block/readers/selector_reader/selector_argument_reader.rs:72:9
  41: <rust_application::input_file::block::readers::selector_reader::SelectorReader as rust_application::input_file::block::readers::char_reader::CharReader>::read
             at ./src/input_file/block/readers/selector_reader.rs:36:28
  42: rust_application::input_file::block::Block::from_string
             at ./src/input_file/block.rs:61:26
  43: rust_application::input_file::BssFile::to_block::{{closure}}
             at ./src/input_file/mod.rs:26:25
  44: scoped_tls::ScopedKey<T>::set
             at /Users/some_user/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.1/src/lib.rs:137:9
  45: rust_application::input_file::BssFile::to_block
             at ./src/input_file/mod.rs:25:9
  46: rust_application::input_file::cli_run_mcfunction::cli_run_mcfunction
             at ./src/input_file/cli_run_mcfunction.rs:7:5
  47: rust_application::cli::run
             at ./src/cli/mod.rs:18:38
  48: rust_application::main
             at ./src/main.rs:50:18
  49: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

</details>

**Comment by rster2002** [comment]
Looking to the code where the panic happens, I think this might be an issue on my side.
